"""Generate cube.xml with randomized sticker colors.

2x2 cube has 8 corner cubelets; each shows 3 outward faces. We sample
3 distinct colors per cubelet from a 6-color Rubik palette so no
cubelet has two same-colored faces. Cubelets in the top half hang off
the rotating ``top`` body; cubelets in the bottom half attach to
``root`` so they don't rotate with the face hinge.

Usage:
    python -m mujoco_sim.build_cube [--seed N]
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

# Rubik palette.
PALETTE: dict[str, tuple[float, float, float]] = {
    "W": (1.00, 1.00, 1.00),
    "Y": (1.00, 0.95, 0.20),
    "R": (0.90, 0.15, 0.15),
    "O": (1.00, 0.50, 0.10),
    "B": (0.15, 0.40, 1.00),
    "G": (0.15, 0.75, 0.25),
}

HALF = 0.0125        # half-cubelet (one cubelet = 25 mm; full cube = 50 mm)
OFFSET = 0.0005      # sticker offset along outward normal (avoid z-fight)
THICK = 0.0005       # sticker half-thickness
WIDE = 0.010         # sticker half-width on each face (in-plane)

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "src/mujoco_sim/assets/cube/cube.xml"


def _geom_line(pos, size, rgb) -> str:
    return (
        f'        <geom class="cube_sticker" type="box" '
        f'pos="{pos[0]:+.4f} {pos[1]:+.4f} {pos[2]:+.4f}" '
        f'size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}" '
        f'rgba="{rgb[0]:.2f} {rgb[1]:.2f} {rgb[2]:.2f} 1"/>'
    )


def _cubelet_stickers(sx: int, sy: int, sz: int, colors: list[str]) -> list[str]:
    """Three sticker geoms for one corner cubelet (sx,sy,sz in {-1, +1}).
    ``colors[0/1/2]`` -> z/x/y outward face respectively."""
    cx, cy, cz = sx * HALF, sy * HALF, sz * HALF
    z_pos = (cx, cy, cz + sz * (HALF + OFFSET))
    x_pos = (cx + sx * (HALF + OFFSET), cy, cz)
    y_pos = (cx, cy + sy * (HALF + OFFSET), cz)
    z_size = (WIDE, WIDE, THICK)
    x_size = (THICK, WIDE, WIDE)
    y_size = (WIDE, THICK, WIDE)
    return [
        _geom_line(z_pos, z_size, PALETTE[colors[0]]),
        _geom_line(x_pos, x_size, PALETTE[colors[1]]),
        _geom_line(y_pos, y_size, PALETTE[colors[2]]),
    ]


def build(seed: int) -> str:
    rng = random.Random(seed)
    keys = list(PALETTE.keys())

    top_lines: list[str] = []
    bottom_lines: list[str] = []
    for sx in (+1, -1):
        for sy in (+1, -1):
            for sz in (+1, -1):
                colors = rng.sample(keys, 3)  # 3 distinct out of 6
                lines = _cubelet_stickers(sx, sy, sz, colors)
                (top_lines if sz == +1 else bottom_lines).extend(lines)

    return f"""<mujoco model="cube_2x2">
  <!-- AUTO-GENERATED by build_cube.py (seed={seed}). Do not edit by hand.
       2x2 cube as two stacked half-cubes joined by a hinge along local
       +z. Stickers cover all 24 outward faces of the 8 corner cubelets;
       each cubelet's 3 faces are guaranteed-distinct colors. -->

  <default>
    <default class="cube_geom">
      <geom condim="4" friction="1.2 0.05 0.001" solref="0.01 1"/>
    </default>
    <default class="cube_sticker">
      <geom contype="0" conaffinity="0" group="1"/>
    </default>
  </default>

  <worldbody>
    <body name="root">
      <freejoint name="free"/>
      <inertial pos="0 0 -0.0125" mass="0.034" diaginertia="9e-6 9e-6 1.4e-5"/>
      <geom name="bottom" class="cube_geom" type="box"
            pos="0 0 -0.0125" size="0.025 0.025 0.0125"
            rgba="0.10 0.10 0.10 1"/>

      <!-- Bottom-half stickers (do not rotate with the hinge). -->
{chr(10).join(bottom_lines)}

      <body name="top">
        <joint name="face" type="hinge" axis="0 0 1"
               frictionloss="0.02" damping="0.002" limited="false"/>
        <inertial pos="0 0 0.0125" mass="0.034" diaginertia="9e-6 9e-6 1.4e-5"/>
        <geom name="top" class="cube_geom" type="box"
              pos="0 0 0.0125" size="0.025 0.025 0.0125"
              rgba="0.10 0.10 0.10 1"/>

        <!-- Top-half stickers (rotate with the face hinge). -->
{chr(10).join(top_lines)}
      </body>
    </body>
  </worldbody>
</mujoco>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    xml = build(args.seed)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(xml)
    print(f"wrote {OUT}  (seed={args.seed})")


if __name__ == "__main__":
    main()
