name: mujoco_sim
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - scipy
  - pyyaml
  - ffmpeg
  - pinocchio
  - pip:
      - -e ./third_party/lerobot[training,diffusion]
      - mujoco
      - imageio
      - gradio
