#!/usr/bin/env python3
"""Prepare an exact-frame VACE robot-embodiment comparison trial.

The script has two stages:

1. ``extract`` creates an 81-frame full-resolution clip and slices the HaWoR
   prompt arrays.  The resulting directory can be passed to
   ``src/inpainting/segment_arms.py`` to regenerate a temporally consistent
   human hand/arm mask.
2. ``finalize`` converts that mask and the existing geometric robot render to
   VACE's 480p inputs.  White mask pixels are generated by VACE, black pixels
   are retained, and masked source pixels are filled with neutral gray (127).

Nothing is written into the original dataset or overlay directories.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import cv2
import numpy as np


DEFAULT_RAW = Path("26.07.27/07_27-26.mp4")
DEFAULT_PROCESSED = Path(
    "data/robot_overlay/kitchen_0724_0728/0727/07_27-26/"
    "inpainting_processed/07_27-26/0"
)
DEFAULT_OUTPUT = Path("output/model_compare/vace/07_27-26_cup_f183_263")


def _open_video(path: Path) -> cv2.VideoCapture:
    cap = cv2.VideoCapture(str(path))
    if not cap.isOpened():
        raise FileNotFoundError(f"Could not open video: {path}")
    return cap


def _video_info(path: Path) -> tuple[int, float, int, int]:
    cap = _open_video(path)
    info = (
        int(cap.get(cv2.CAP_PROP_FRAME_COUNT)),
        float(cap.get(cv2.CAP_PROP_FPS)),
        int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)),
    )
    cap.release()
    return info


def _writer(path: Path, fps: float, size: tuple[int, int], color: bool = True):
    path.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(
        str(path), cv2.VideoWriter_fourcc(*"mp4v"), fps, size, color
    )
    if not writer.isOpened():
        raise RuntimeError(f"Could not create video: {path}")
    return writer


def _read_range(path: Path, first: int, last: int) -> tuple[list[np.ndarray], float]:
    count, fps, _, _ = _video_info(path)
    if not (0 <= first <= last < count):
        raise ValueError(f"Requested frames {first}:{last}, but {path} has {count}")
    cap = _open_video(path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, first)
    frames = []
    for frame_index in range(first, last + 1):
        ok, frame = cap.read()
        if not ok:
            raise RuntimeError(f"Failed to decode frame {frame_index} from {path}")
        frames.append(frame)
    cap.release()
    return frames, fps


def _write_video(path: Path, frames: list[np.ndarray], fps: float) -> None:
    if not frames:
        raise ValueError("No frames to write")
    height, width = frames[0].shape[:2]
    writer = _writer(path, fps, (width, height))
    for frame in frames:
        writer.write(frame)
    writer.release()


def _slice_npz(source: Path, target: Path, first: int, last: int) -> None:
    arrays = np.load(source, allow_pickle=True)
    output = {}
    expected = None
    for key in arrays.files:
        value = arrays[key]
        if value.ndim > 0 and value.shape[0] > last:
            expected = value.shape[0] if expected is None else expected
            output[key] = value[first : last + 1]
        else:
            output[key] = value
    if expected is None:
        raise ValueError(f"No frame-aligned arrays found in {source}")
    target.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(target, **output)


def extract(args: argparse.Namespace) -> None:
    frame_count = args.last_frame - args.first_frame + 1
    if frame_count % 4 != 1:
        raise ValueError(f"VACE needs 4n+1 frames; requested {frame_count}")

    raw_frames, fps = _read_range(args.raw_video, args.first_frame, args.last_frame)
    work = args.output / "sam2_work"
    _write_video(work / "video_L.mp4", raw_frames, fps)

    for relative in (
        Path("bbox_processor/bbox_data.npz"),
        Path("hand_processor/hand_data_left.npz"),
        Path("hand_processor/hand_data_right.npz"),
    ):
        _slice_npz(
            args.processed_demo / relative,
            work / relative,
            args.first_frame,
            args.last_frame,
        )

    overlay = args.processed_demo / "video_overlay_robot_unclipped.mp4"
    robot_only = args.processed_demo / "overlay_processor/video_robot_only.mp4"
    overlay_frames, overlay_fps = _read_range(
        overlay, args.first_frame, args.last_frame
    )
    robot_frames, _ = _read_range(robot_only, args.first_frame, args.last_frame)
    _write_video(args.output / "geometric_overlay_81f.mp4", overlay_frames, overlay_fps)
    _write_video(args.output / "robot_only_81f.mp4", robot_frames, overlay_fps)

    manifest = {
        "source_video": str(args.raw_video.resolve()),
        "processed_demo": str(args.processed_demo.resolve()),
        "first_frame_inclusive": args.first_frame,
        "last_frame_inclusive": args.last_frame,
        "frame_count": frame_count,
        "source_fps": fps,
        "semantic_interval": "Cup skill; GT frames 196-250, with transition context",
        "sam2_command": (
            "conda run -n inpaint-gpu python src/inpainting/segment_arms.py "
            f"--processed_demo {work}"
        ),
    }
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(f"[ok] extracted {frame_count} frames to {args.output}")


def _fit_480p(frame: np.ndarray, size: tuple[int, int]) -> np.ndarray:
    """Aspect-fill then center-crop, applying one transform to every modality."""
    target_w, target_h = size
    height, width = frame.shape[:2]
    scale = max(target_w / width, target_h / height)
    resized_w = int(round(width * scale))
    resized_h = int(round(height * scale))
    interpolation = cv2.INTER_NEAREST if frame.ndim == 2 else cv2.INTER_AREA
    resized = cv2.resize(frame, (resized_w, resized_h), interpolation=interpolation)
    x0 = (resized_w - target_w) // 2
    y0 = (resized_h - target_h) // 2
    return resized[y0 : y0 + target_h, x0 : x0 + target_w]


def _white_background_robot(frame: np.ndarray) -> np.ndarray:
    """Turn the black background of the geometric robot-only render white."""
    foreground = np.max(frame, axis=2) > 12
    foreground = cv2.morphologyEx(
        foreground.astype(np.uint8),
        cv2.MORPH_CLOSE,
        cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5)),
    ).astype(bool)
    output = np.full_like(frame, 255)
    output[foreground] = frame[foreground]
    return output


def finalize(args: argparse.Namespace) -> None:
    work = args.output / "sam2_work"
    source_frames, fps = _read_range(work / "video_L.mp4", 0, args.frame_count - 1)
    geometric_frames, _ = _read_range(
        args.output / "geometric_overlay_81f.mp4", 0, args.frame_count - 1
    )
    robot_frames, _ = _read_range(
        args.output / "robot_only_81f.mp4", 0, args.frame_count - 1
    )
    masks = np.load(work / "segmentation_processor/masks_arm.npy")
    if masks.shape[0] != args.frame_count:
        raise ValueError(f"Expected {args.frame_count} masks, got {masks.shape}")

    target_size = (args.width, args.height)
    source_writer = _writer(args.output / "vace_src_video.mp4", fps, target_size)
    mask_writer = _writer(args.output / "vace_src_mask.mp4", fps, target_size)
    raw_writer = _writer(args.output / "raw_clip_480p.mp4", fps, target_size)
    geo_writer = _writer(args.output / "geometric_overlay_clip_480p.mp4", fps, target_size)

    mask_coverages = []
    for source, geometric, mask in zip(source_frames, geometric_frames, masks):
        source = _fit_480p(source, target_size)
        geometric = _fit_480p(geometric, target_size)
        mask = (_fit_480p(mask.astype(np.uint8), target_size) > 0).astype(np.uint8)
        if args.dilate > 0:
            kernel = cv2.getStructuringElement(
                cv2.MORPH_ELLIPSE, (2 * args.dilate + 1, 2 * args.dilate + 1)
            )
            mask = cv2.dilate(mask, kernel)
        masked_source = source.copy()
        masked_source[mask > 0] = 127
        mask_bgr = cv2.cvtColor(mask * 255, cv2.COLOR_GRAY2BGR)
        source_writer.write(masked_source)
        mask_writer.write(mask_bgr)
        raw_writer.write(source)
        geo_writer.write(geometric)
        mask_coverages.append(float(mask.mean()))

    for writer in (source_writer, mask_writer, raw_writer, geo_writer):
        writer.release()

    ref_index = int(np.clip(args.reference_frame - args.first_frame, 0, args.frame_count - 1))
    robot_reference = _white_background_robot(robot_frames[ref_index])
    robot_reference = _fit_480p(robot_reference, target_size)
    cv2.imwrite(str(args.output / "robot_reference_white.png"), robot_reference)
    overlay_reference = _fit_480p(geometric_frames[ref_index], target_size)
    cv2.imwrite(str(args.output / "robot_reference_in_scene.png"), overlay_reference)

    manifest_path = args.output / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest.update(
        {
            "vace_size": f"{args.width}x{args.height}",
            "mask_dilation_pixels_at_vace_resolution": args.dilate,
            "mean_editable_fraction": float(np.mean(mask_coverages)),
            "reference_global_frame": args.reference_frame,
            "recommended_reference": "robot_reference_white.png",
            "prompt": (
                "A fixed first-person camera view in a bright real kitchen. A realistic "
                "bimanual robot arm with a compact industrial gripper reaches forward and "
                "grasps the cup, following the exact original hand trajectory. Preserve the "
                "table, cup, objects, lighting, camera, and all unmasked pixels. Photorealistic "
                "robot embodiment, temporally stable geometry, consistent joints and gripper."
            ),
        }
    )
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[ok] finalized VACE inputs in {args.output}")
    print(f"[info] mean editable area: {np.mean(mask_coverages):.2%}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stage", choices=("extract", "finalize"))
    parser.add_argument("--raw-video", type=Path, default=DEFAULT_RAW)
    parser.add_argument("--processed-demo", type=Path, default=DEFAULT_PROCESSED)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--first-frame", type=int, default=183)
    parser.add_argument("--last-frame", type=int, default=263)
    parser.add_argument("--frame-count", type=int, default=81)
    parser.add_argument("--reference-frame", type=int, default=220)
    parser.add_argument("--width", type=int, default=832)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--dilate", type=int, default=10)
    return parser


if __name__ == "__main__":
    parsed = build_parser().parse_args()
    if parsed.stage == "extract":
        extract(parsed)
    else:
        finalize(parsed)
