retargeting:
  type: DexPilot
  urdf_path: xhand/xhand_left.urdf

  wrist_link_name: "left_hand_link"
  finger_tip_link_names:
    - "left_hand_thumb_rota_tip"
    - "left_hand_index_rota_tip"
    - "left_hand_mid_tip"
    - "left_hand_ring_tip"
    - "left_hand_pinky_tip"

  scaling_factor: 1.0
  low_pass_alpha: 0.2
